site_name: BLUX Doctrine
nav:
  - Home: index.md
  - Vision: VISION.md
  - Architecture: ARCHITECTURE.md
  - Policy Model: POLICY_MODEL.md
  - Schema: SCHEMA.md
  - DSL: DSL.md
  - Evaluation: EVALUATION.md
  - Integrations: INTEGRATIONS.md
  - Install: INSTALL.md
  - Operations: OPERATIONS.md
  - Security: SECURITY.md
  - Privacy: PRIVACY.md
  - Configuration: CONFIGURATION.md
  - Troubleshooting: TROUBLESHOOTING.md
  - Roadmap: ROADMAP.md
theme:
  name: material
